# Generated by Django 4.1.7 on 2023-03-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_grid',
            name='author',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
