# Generated by Django 4.1.7 on 2023-03-06 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('email', models.CharField(default=None, max_length=50)),
                ('phonenumber', models.CharField(default=None, max_length=50)),
                ('message', models.TextField()),
            ],
        ),
    ]
