# Generated by Django 4.1.7 on 2023-03-06 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phonenumber',
            field=models.CharField(max_length=10),
        ),
    ]
