# Generated by Django 4.0.6 on 2023-04-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0002_alter_contact_name_alter_contact_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='services',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
