# Generated by Django 4.1.7 on 2023-03-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, default='default.png', upload_to='grid/')),
                ('content', models.TextField()),
                ('Mainimage', models.ImageField(blank=True, default='default.png', upload_to='grid/')),
                ('image1', models.ImageField(blank=True, default='default.png', upload_to='grid/')),
                ('image2', models.ImageField(blank=True, default='default.png', upload_to='grid/')),
                ('image3', models.ImageField(blank=True, default='default.png', upload_to='grid/')),
                ('image4', models.ImageField(blank=True, default='default.png', upload_to='grid/')),
                ('image5', models.ImageField(blank=True, default='default.png', upload_to='grid/')),
                ('image6', models.ImageField(blank=True, default='default.png', upload_to='grid/')),
            ],
        ),
    ]
