# Generated by Django 4.1.7 on 2023-03-08 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliodetails',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.grid'),
        ),
    ]
